package org.tongji.anliantest.model;

// Generated 2013-11-20 5:24:58 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DepartmentInfo generated by hbm2java
 */
@Entity
@Table(name = "Department_Info", catalog = "anliantest")
public class DepartmentInfo implements java.io.Serializable {

	private Integer dpId;
	private String dpName;
	private String dpDescription;
	private Set<EmployeeInfo> employeeInfos = new HashSet<EmployeeInfo>(0);

	public DepartmentInfo() {
	}

	public DepartmentInfo(String dpName, String dpDescription,
			Set<EmployeeInfo> employeeInfos) {
		this.dpName = dpName;
		this.dpDescription = dpDescription;
		this.employeeInfos = employeeInfos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "DP_ID", unique = true, nullable = false)
	public Integer getDpId() {
		return this.dpId;
	}

	public void setDpId(Integer dpId) {
		this.dpId = dpId;
	}

	@Column(name = "DP_Name", length = 100)
	public String getDpName() {
		return this.dpName;
	}

	public void setDpName(String dpName) {
		this.dpName = dpName;
	}

	@Column(name = "DP_Description")
	public String getDpDescription() {
		return this.dpDescription;
	}

	public void setDpDescription(String dpDescription) {
		this.dpDescription = dpDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departmentInfo")
	public Set<EmployeeInfo> getEmployeeInfos() {
		return this.employeeInfos;
	}

	public void setEmployeeInfos(Set<EmployeeInfo> employeeInfos) {
		this.employeeInfos = employeeInfos;
	}

}
