package org.tongji.anliantest.model;

// Generated 2013-11-23 6:49:31 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmployeeInfo generated by hbm2java
 */
@Entity
@Table(name = "Employee_Info", catalog = "anliantest")
public class EmployeeInfo implements java.io.Serializable {

	private Integer epId;
	private DepartmentInfo departmentInfo;
	private String epNumber;
	private String epName;
	private String epPassword;
	private String epTitle;

	public EmployeeInfo() {
	}

	public EmployeeInfo(String epNumber, String epName, String epPassword) {
		this.epNumber = epNumber;
		this.epName = epName;
		this.epPassword = epPassword;
	}

	public EmployeeInfo(DepartmentInfo departmentInfo, String epNumber,
			String epName, String epPassword, String epTitle) {
		this.departmentInfo = departmentInfo;
		this.epNumber = epNumber;
		this.epName = epName;
		this.epPassword = epPassword;
		this.epTitle = epTitle;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "EP_ID", unique = true, nullable = false)
	public Integer getEpId() {
		return this.epId;
	}

	public void setEpId(Integer epId) {
		this.epId = epId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DP_ID")
	public DepartmentInfo getDepartmentInfo() {
		return this.departmentInfo;
	}

	public void setDepartmentInfo(DepartmentInfo departmentInfo) {
		this.departmentInfo = departmentInfo;
	}

	@Column(name = "EP_Number", nullable = false, length = 6)
	public String getEpNumber() {
		return this.epNumber;
	}

	public void setEpNumber(String epNumber) {
		this.epNumber = epNumber;
	}

	@Column(name = "EP_Name", nullable = false, length = 100)
	public String getEpName() {
		return this.epName;
	}

	public void setEpName(String epName) {
		this.epName = epName;
	}

	@Column(name = "EP_PASSWORD", nullable = false, length = 100)
	public String getEpPassword() {
		return this.epPassword;
	}

	public void setEpPassword(String epPassword) {
		this.epPassword = epPassword;
	}

	@Column(name = "EP_Title", length = 100)
	public String getEpTitle() {
		return this.epTitle;
	}

	public void setEpTitle(String epTitle) {
		this.epTitle = epTitle;
	}

}
