package edu.tongji.anliantest.model;

// Generated 2013-12-8 15:43:04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DepartmentInfo generated by hbm2java
 */
@Entity
@Table(name = "department_info", catalog = "anliantest")
public class DepartmentInfo implements java.io.Serializable {

	private Integer departmentId;
	private String departmentName;
	private String departmentDesc;
	private Set<EmployeeInfo> employeeInfos = new HashSet<EmployeeInfo>(0);

	public DepartmentInfo() {
	}

	public DepartmentInfo(String departmentName) {
		this.departmentName = departmentName;
	}

	public DepartmentInfo(String departmentName, String departmentDesc,
			Set<EmployeeInfo> employeeInfos) {
		this.departmentName = departmentName;
		this.departmentDesc = departmentDesc;
		this.employeeInfos = employeeInfos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "department_id", unique = true, nullable = false)
	public Integer getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "department_name", nullable = false, length = 45)
	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	@Column(name = "department_desc")
	public String getDepartmentDesc() {
		return this.departmentDesc;
	}

	public void setDepartmentDesc(String departmentDesc) {
		this.departmentDesc = departmentDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departmentInfo")
	public Set<EmployeeInfo> getEmployeeInfos() {
		return this.employeeInfos;
	}

	public void setEmployeeInfos(Set<EmployeeInfo> employeeInfos) {
		this.employeeInfos = employeeInfos;
	}

}
