package edu.tongji.anliantest.model;

// Generated 2013-12-8 15:43:04 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EmployeeInfo generated by hbm2java
 */
@Entity
@Table(name = "employee_info", catalog = "anliantest", uniqueConstraints = @UniqueConstraint(columnNames = "employee_number"))
public class EmployeeInfo implements java.io.Serializable {

	private Integer employeeId;
	private DepartmentInfo departmentInfo;
	private String employeeNumber;
	private String employeeName;
	private String employeePassword;
	private String employeeTitle;
	private String employeeAvatar;

	public EmployeeInfo() {
	}

	public EmployeeInfo(String employeeNumber, String employeeName,
			String employeePassword) {
		this.employeeNumber = employeeNumber;
		this.employeeName = employeeName;
		this.employeePassword = employeePassword;
	}

	public EmployeeInfo(DepartmentInfo departmentInfo, String employeeNumber,
			String employeeName, String employeePassword, String employeeTitle,
			String employeeAvatar) {
		this.departmentInfo = departmentInfo;
		this.employeeNumber = employeeNumber;
		this.employeeName = employeeName;
		this.employeePassword = employeePassword;
		this.employeeTitle = employeeTitle;
		this.employeeAvatar = employeeAvatar;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "employee_id", unique = true, nullable = false)
	public Integer getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "department_id")
	public DepartmentInfo getDepartmentInfo() {
		return this.departmentInfo;
	}

	public void setDepartmentInfo(DepartmentInfo departmentInfo) {
		this.departmentInfo = departmentInfo;
	}

	@Column(name = "employee_number", unique = true, nullable = false, length = 45)
	public String getEmployeeNumber() {
		return this.employeeNumber;
	}

	public void setEmployeeNumber(String employeeNumber) {
		this.employeeNumber = employeeNumber;
	}

	@Column(name = "employee_name", nullable = false, length = 45)
	public String getEmployeeName() {
		return this.employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	@Column(name = "employee_password", nullable = false, length = 45)
	public String getEmployeePassword() {
		return this.employeePassword;
	}

	public void setEmployeePassword(String employeePassword) {
		this.employeePassword = employeePassword;
	}

	@Column(name = "employee_title", length = 45)
	public String getEmployeeTitle() {
		return this.employeeTitle;
	}

	public void setEmployeeTitle(String employeeTitle) {
		this.employeeTitle = employeeTitle;
	}

	@Column(name = "employee_avatar")
	public String getEmployeeAvatar() {
		return this.employeeAvatar;
	}

	public void setEmployeeAvatar(String employeeAvatar) {
		this.employeeAvatar = employeeAvatar;
	}

}
