package edu.tongji.anliantest.model;

// Generated 2014-3-14 19:09:28 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SamplePlanItem generated by hbm2java
 */
@Entity
@Table(name = "sample_plan_item", catalog = "anliantest")
public class SamplePlanItem implements java.io.Serializable {

	private int itemId;
	private HarmfulSubstanceNationalStandardTable harmfulSubstanceNationalStandardTable;
	private String sampleWorkshopJob;
	private Integer sampleDeviceId;
	private String sampleDeviceName;
	private String sampleStandard;
	private BigDecimal sampleTime;
	private BigDecimal sampleFlow;
	private Integer collectDeviceId;
	private String collectDeviceName;
	private Integer sampleCount;
	private String sampleNum;
	private String sampleSaveMethod;
	private String sampleComment;

	public SamplePlanItem() {
	}

	public SamplePlanItem(int itemId) {
		this.itemId = itemId;
	}

	public SamplePlanItem(
			int itemId,
			HarmfulSubstanceNationalStandardTable harmfulSubstanceNationalStandardTable,
			String sampleWorkshopJob, Integer sampleDeviceId,
			String sampleDeviceName, String sampleStandard,
			BigDecimal sampleTime, BigDecimal sampleFlow,
			Integer collectDeviceId, String collectDeviceName,
			Integer sampleCount, String sampleNum, String sampleSaveMethod,
			String sampleComment) {
		this.itemId = itemId;
		this.harmfulSubstanceNationalStandardTable = harmfulSubstanceNationalStandardTable;
		this.sampleWorkshopJob = sampleWorkshopJob;
		this.sampleDeviceId = sampleDeviceId;
		this.sampleDeviceName = sampleDeviceName;
		this.sampleStandard = sampleStandard;
		this.sampleTime = sampleTime;
		this.sampleFlow = sampleFlow;
		this.collectDeviceId = collectDeviceId;
		this.collectDeviceName = collectDeviceName;
		this.sampleCount = sampleCount;
		this.sampleNum = sampleNum;
		this.sampleSaveMethod = sampleSaveMethod;
		this.sampleComment = sampleComment;
	}

	@Id
	@Column(name = "item_id", unique = true, nullable = false)
	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "substance_id")
	public HarmfulSubstanceNationalStandardTable getHarmfulSubstanceNationalStandardTable() {
		return this.harmfulSubstanceNationalStandardTable;
	}

	public void setHarmfulSubstanceNationalStandardTable(
			HarmfulSubstanceNationalStandardTable harmfulSubstanceNationalStandardTable) {
		this.harmfulSubstanceNationalStandardTable = harmfulSubstanceNationalStandardTable;
	}

	@Column(name = "sample_workshop_job", length = 100)
	public String getSampleWorkshopJob() {
		return this.sampleWorkshopJob;
	}

	public void setSampleWorkshopJob(String sampleWorkshopJob) {
		this.sampleWorkshopJob = sampleWorkshopJob;
	}

	@Column(name = "sample_device_id")
	public Integer getSampleDeviceId() {
		return this.sampleDeviceId;
	}

	public void setSampleDeviceId(Integer sampleDeviceId) {
		this.sampleDeviceId = sampleDeviceId;
	}

	@Column(name = "sample_device_name", length = 100)
	public String getSampleDeviceName() {
		return this.sampleDeviceName;
	}

	public void setSampleDeviceName(String sampleDeviceName) {
		this.sampleDeviceName = sampleDeviceName;
	}

	@Column(name = "sample_standard", length = 100)
	public String getSampleStandard() {
		return this.sampleStandard;
	}

	public void setSampleStandard(String sampleStandard) {
		this.sampleStandard = sampleStandard;
	}

	@Column(name = "sample_time", precision = 4, scale = 4)
	public BigDecimal getSampleTime() {
		return this.sampleTime;
	}

	public void setSampleTime(BigDecimal sampleTime) {
		this.sampleTime = sampleTime;
	}

	@Column(name = "sample_flow", precision = 4, scale = 4)
	public BigDecimal getSampleFlow() {
		return this.sampleFlow;
	}

	public void setSampleFlow(BigDecimal sampleFlow) {
		this.sampleFlow = sampleFlow;
	}

	@Column(name = "collect_device_id")
	public Integer getCollectDeviceId() {
		return this.collectDeviceId;
	}

	public void setCollectDeviceId(Integer collectDeviceId) {
		this.collectDeviceId = collectDeviceId;
	}

	@Column(name = "collect_device_name", length = 100)
	public String getCollectDeviceName() {
		return this.collectDeviceName;
	}

	public void setCollectDeviceName(String collectDeviceName) {
		this.collectDeviceName = collectDeviceName;
	}

	@Column(name = "sample_count")
	public Integer getSampleCount() {
		return this.sampleCount;
	}

	public void setSampleCount(Integer sampleCount) {
		this.sampleCount = sampleCount;
	}

	@Column(name = "sample_num", length = 100)
	public String getSampleNum() {
		return this.sampleNum;
	}

	public void setSampleNum(String sampleNum) {
		this.sampleNum = sampleNum;
	}

	@Column(name = "sample_save_method", length = 100)
	public String getSampleSaveMethod() {
		return this.sampleSaveMethod;
	}

	public void setSampleSaveMethod(String sampleSaveMethod) {
		this.sampleSaveMethod = sampleSaveMethod;
	}

	@Column(name = "sample_comment")
	public String getSampleComment() {
		return this.sampleComment;
	}

	public void setSampleComment(String sampleComment) {
		this.sampleComment = sampleComment;
	}

}
