package edu.tongji.anliantest.model;

// Generated 2013-12-8 15:43:04 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SystemRole generated by hbm2java
 */
@Entity
@Table(name = "system_role", catalog = "anliantest", uniqueConstraints = @UniqueConstraint(columnNames = "role_name"))
public class SystemRole implements java.io.Serializable {

	private Integer roleId;
	private String roleName;

	public SystemRole() {
	}

	public SystemRole(String roleName) {
		this.roleName = roleName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "role_id", unique = true, nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role_name", unique = true, nullable = false, length = 45)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

}
