package edu.tongji.anliantest.model;

// Generated 2014-3-20 13:25:31 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TestDataProcessItem generated by hbm2java
 */
@Entity
@Table(name = "test_data_process_item", catalog = "anliantest")
public class TestDataProcessItem implements java.io.Serializable {

	private int itemId;
	private TestDataProcessGroup testDataProcessGroup;
	private Integer testSampleId;
	private String testSampleNum;
	private BigDecimal testResult;
	private String testResultType;
	private BigDecimal testTouchTime;
	private Integer testTouchTimeScale;
	private Integer testResultScale;

	public TestDataProcessItem() {
	}

	public TestDataProcessItem(int itemId) {
		this.itemId = itemId;
	}

	public TestDataProcessItem(int itemId,
			TestDataProcessGroup testDataProcessGroup, Integer testSampleId,
			String testSampleNum, BigDecimal testResult, String testResultType,
			BigDecimal testTouchTime, Integer testTouchTimeScale,
			Integer testResultScale) {
		this.itemId = itemId;
		this.testDataProcessGroup = testDataProcessGroup;
		this.testSampleId = testSampleId;
		this.testSampleNum = testSampleNum;
		this.testResult = testResult;
		this.testResultType = testResultType;
		this.testTouchTime = testTouchTime;
		this.testTouchTimeScale = testTouchTimeScale;
		this.testResultScale = testResultScale;
	}

	@Id
	@Column(name = "item_id", unique = true, nullable = false)
	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_id")
	public TestDataProcessGroup getTestDataProcessGroup() {
		return this.testDataProcessGroup;
	}

	public void setTestDataProcessGroup(
			TestDataProcessGroup testDataProcessGroup) {
		this.testDataProcessGroup = testDataProcessGroup;
	}

	@Column(name = "test_sample_id")
	public Integer getTestSampleId() {
		return this.testSampleId;
	}

	public void setTestSampleId(Integer testSampleId) {
		this.testSampleId = testSampleId;
	}

	@Column(name = "test_sample_num", length = 100)
	public String getTestSampleNum() {
		return this.testSampleNum;
	}

	public void setTestSampleNum(String testSampleNum) {
		this.testSampleNum = testSampleNum;
	}

	@Column(name = "test_result", precision = 14, scale = 8)
	public BigDecimal getTestResult() {
		return this.testResult;
	}

	public void setTestResult(BigDecimal testResult) {
		this.testResult = testResult;
	}

	@Column(name = "test_result_type", length = 2)
	public String getTestResultType() {
		return this.testResultType;
	}

	public void setTestResultType(String testResultType) {
		this.testResultType = testResultType;
	}

	@Column(name = "test_touch_time", precision = 7, scale = 4)
	public BigDecimal getTestTouchTime() {
		return this.testTouchTime;
	}

	public void setTestTouchTime(BigDecimal testTouchTime) {
		this.testTouchTime = testTouchTime;
	}

	@Column(name = "test_touch_time_scale")
	public Integer getTestTouchTimeScale() {
		return this.testTouchTimeScale;
	}

	public void setTestTouchTimeScale(Integer testTouchTimeScale) {
		this.testTouchTimeScale = testTouchTimeScale;
	}

	@Column(name = "test_result_scale")
	public Integer getTestResultScale() {
		return this.testResultScale;
	}

	public void setTestResultScale(Integer testResultScale) {
		this.testResultScale = testResultScale;
	}

}
