package edu.tongji.anliantest.model;

// Generated 2014-3-14 19:09:28 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TestReportTable generated by hbm2java
 */
public class TestReportTableData implements java.io.Serializable {

	private int tableId;
	//private EmployeeInfo employeeInfoBySignerId;
	//private ProjectInfo projectInfo;
	//private EmployeeInfo employeeInfoByReviewerId;
	//private EmployeeInfo employeeInfoByPreparerId;
	private String signerName;
	private String reviewerName;
	private String prepareName;
	private String testReportNum;
	private String sampleName;
	private Integer sampleNum;
	private String sampleStatus;
	private String testProperty;
	private String testUnitName;
	private String testUnitAddress;
	private String entrustUnitName;
	private Date sampleTime;
	private Date receiveTime;
	private Date testTimeStart;
	private Date testTimeEnd;
	private Date reportTime;
	private Date tableTime;
	//private Set<TestReportItem> testReportItems = new HashSet<TestReportItem>(0);

	public TestReportTableData() {
	}

	public TestReportTableData(int tableId) {
		this.tableId = tableId;
	}

	public TestReportTableData(int tableId, String signerName,
			String reviewerName, String prepareName, String testReportNum,
			String sampleName, Integer sampleNum, String sampleStatus,
			String testProperty, String testUnitName, String testUnitAddress,
			String entrustUnitName, Date sampleTime, Date receiveTime,
			Date testTimeStart, Date testTimeEnd, Date reportTime, Date tableTime) {
		super();
		this.tableId = tableId;
		this.signerName = signerName;
		this.reviewerName = reviewerName;
		this.prepareName = prepareName;
		this.testReportNum = testReportNum;
		this.sampleName = sampleName;
		this.sampleNum = sampleNum;
		this.sampleStatus = sampleStatus;
		this.testProperty = testProperty;
		this.testUnitName = testUnitName;
		this.testUnitAddress = testUnitAddress;
		this.entrustUnitName = entrustUnitName;
		this.sampleTime = sampleTime;
		this.receiveTime = receiveTime;
		this.testTimeStart = testTimeStart;
		this.testTimeEnd = testTimeEnd;
		this.reportTime = reportTime;
		this.tableTime = tableTime;
	}

	public int getTableId() {
		return tableId;
	}

	public void setTableId(int tableId) {
		this.tableId = tableId;
	}

	public String getSignerName() {
		return signerName;
	}

	public void setSignerName(String signerName) {
		this.signerName = signerName;
	}

	public String getReviewerName() {
		return reviewerName;
	}

	public void setReviewerName(String reviewerName) {
		this.reviewerName = reviewerName;
	}

	public String getPrepareName() {
		return prepareName;
	}

	public void setPrepareName(String prepareName) {
		this.prepareName = prepareName;
	}

	public String getTestReportNum() {
		return testReportNum;
	}

	public void setTestReportNum(String testReportNum) {
		this.testReportNum = testReportNum;
	}

	public String getSampleName() {
		return sampleName;
	}

	public void setSampleName(String sampleName) {
		this.sampleName = sampleName;
	}

	public Integer getSampleNum() {
		return sampleNum;
	}

	public void setSampleNum(Integer sampleNum) {
		this.sampleNum = sampleNum;
	}

	public String getSampleStatus() {
		return sampleStatus;
	}

	public void setSampleStatus(String sampleStatus) {
		this.sampleStatus = sampleStatus;
	}

	public String getTestProperty() {
		return testProperty;
	}

	public void setTestProperty(String testProperty) {
		this.testProperty = testProperty;
	}

	public String getTestUnitName() {
		return testUnitName;
	}

	public void setTestUnitName(String testUnitName) {
		this.testUnitName = testUnitName;
	}

	public String getTestUnitAddress() {
		return testUnitAddress;
	}

	public void setTestUnitAddress(String testUnitAddress) {
		this.testUnitAddress = testUnitAddress;
	}

	public String getEntrustUnitName() {
		return entrustUnitName;
	}

	public void setEntrustUnitName(String entrustUnitName) {
		this.entrustUnitName = entrustUnitName;
	}

	public Date getSampleTime() {
		return sampleTime;
	}

	public void setSampleTime(Date sampleTime) {
		this.sampleTime = sampleTime;
	}

	public Date getReceiveTime() {
		return receiveTime;
	}

	public void setReceiveTime(Date receiveTime) {
		this.receiveTime = receiveTime;
	}

	public Date getTestTimeStart() {
		return testTimeStart;
	}

	public void setTestTimeStart(Date testTimeStart) {
		this.testTimeStart = testTimeStart;
	}

	public Date getTestTimeEnd() {
		return testTimeEnd;
	}

	public void setTestTimeEnd(Date testTimeEnd) {
		this.testTimeEnd = testTimeEnd;
	}

	public Date getReportTime() {
		return reportTime;
	}

	public void setReportTime(Date reportTime) {
		this.reportTime = reportTime;
	}

	public Date getTableTime() {
		return tableTime;
	}

	public void setTableTime(Date tableTime) {
		this.tableTime = tableTime;
	}

	
}
