package edu.tongji.anliantest.model;

// Generated 2014-3-14 19:09:28 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TestDataResultTable generated by hbm2java
 */
@Entity
@Table(name = "test_data_result_table", catalog = "anliantest")
public class TestDataResultTable implements java.io.Serializable {

	private int tableId;
	private ProjectInfo projectInfo;
	private String tableName;
	private Set<TestDataResultItem> testDataResultItems = new HashSet<TestDataResultItem>(
			0);

	public TestDataResultTable() {
	}

	public TestDataResultTable(int tableId) {
		this.tableId = tableId;
	}

	public TestDataResultTable(int tableId, ProjectInfo projectInfo,
			String tableName, Set<TestDataResultItem> testDataResultItems) {
		this.tableId = tableId;
		this.projectInfo = projectInfo;
		this.tableName = tableName;
		this.testDataResultItems = testDataResultItems;
	}

	@Id
	@Column(name = "table_id", unique = true, nullable = false)
	public int getTableId() {
		return this.tableId;
	}

	public void setTableId(int tableId) {
		this.tableId = tableId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	public ProjectInfo getProjectInfo() {
		return this.projectInfo;
	}

	public void setProjectInfo(ProjectInfo projectInfo) {
		this.projectInfo = projectInfo;
	}

	@Column(name = "table_name", length = 100)
	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "testDataResultTable")
	public Set<TestDataResultItem> getTestDataResultItems() {
		return this.testDataResultItems;
	}

	public void setTestDataResultItems(
			Set<TestDataResultItem> testDataResultItems) {
		this.testDataResultItems = testDataResultItems;
	}

}
