package edu.tongji.anliantest.model;

// Generated 2014-3-14 19:09:28 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkTaskTable generated by hbm2java
 */
@Entity
@Table(name = "work_task_table", catalog = "anliantest")
public class WorkTaskTable implements java.io.Serializable {

	private int tableId;
	private ProjectInfo projectInfo;
	private EmployeeInfo employeeInfo;
	private String tableNum;
	private String tableType;
	private Date taskTime;
	private Set<WorkTaskItem> workTaskItems = new HashSet<WorkTaskItem>(0);

	public WorkTaskTable() {
	}

	public WorkTaskTable(int tableId) {
		this.tableId = tableId;
	}

	public WorkTaskTable(int tableId, ProjectInfo projectInfo,
			EmployeeInfo employeeInfo, String tableNum, String tableType,
			Date taskTime, Set<WorkTaskItem> workTaskItems) {
		this.tableId = tableId;
		this.projectInfo = projectInfo;
		this.employeeInfo = employeeInfo;
		this.tableNum = tableNum;
		this.tableType = tableType;
		this.taskTime = taskTime;
		this.workTaskItems = workTaskItems;
	}

	@Id
	@Column(name = "table_id", unique = true, nullable = false)
	public int getTableId() {
		return this.tableId;
	}

	public void setTableId(int tableId) {
		this.tableId = tableId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	public ProjectInfo getProjectInfo() {
		return this.projectInfo;
	}

	public void setProjectInfo(ProjectInfo projectInfo) {
		this.projectInfo = projectInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "task_employee_id")
	public EmployeeInfo getEmployeeInfo() {
		return this.employeeInfo;
	}

	public void setEmployeeInfo(EmployeeInfo employeeInfo) {
		this.employeeInfo = employeeInfo;
	}

	@Column(name = "table_num", length = 13)
	public String getTableNum() {
		return this.tableNum;
	}

	public void setTableNum(String tableNum) {
		this.tableNum = tableNum;
	}

	@Column(name = "table_type", length = 3)
	public String getTableType() {
		return this.tableType;
	}

	public void setTableType(String tableType) {
		this.tableType = tableType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "task_time", length = 19)
	public Date getTaskTime() {
		return this.taskTime;
	}

	public void setTaskTime(Date taskTime) {
		this.taskTime = taskTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workTaskTable")
	public Set<WorkTaskItem> getWorkTaskItems() {
		return this.workTaskItems;
	}

	public void setWorkTaskItems(Set<WorkTaskItem> workTaskItems) {
		this.workTaskItems = workTaskItems;
	}

}
